spring:
  application:
    name: ms-order
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  order-notification: order-notification-queue
  payment-notification: payment-notification-queue

